repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "100"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.12.0
    hooks:
      - id: eslint
