name: Bump Version Reaction

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.post[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+[a-b][0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  bump-react:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Debug
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        NAME=$(git for-each-ref $GITHUB_REF_NAME --shell --format='%(taggername)')
        echo "name: $NAME"
        EMAIL=$(git for-each-ref $GITHUB_REF_NAME --shell --format='%(taggeremail)')
        echo "email: $EMAIL"
