name: Debug
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  debug:
    runs-on: ubuntu-20.04
    permissions:
        contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: "Describe user"
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          name=$(gh api user --jq '.name')
          echo "$name"
          echo "$GITHUB_ACTOR"
