name: Check
on:
  push:
    branches: "main"
  pull_request:
    branches: "*"
jobs:
  # Run "pre-commit run --all-files"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
