name: Test PR Comment
on:
  pull_request_target:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
    steps:
    - uses: actions/checkout@v2
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: "test pr comment"

    - name: Create the comment body
      run: |
        bash test.sh
    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: 'test.txt'
        edit-mode: replace
