name: Trigger Pre-Commit on a PR
on:
  issue_comment:
    types: [created]
jobs:
  pr-script:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@1.0.0
        id: check
        with:
          trigger: 'auto run pre-commit'
      - uses: actions/checkout@v2
      - name: Print Issue Url
        run: |
            echo "$${{ github.event.issue.html_url }}"
      - if: steps.check.outputs.triggered == 'true'
        uses: ./.github/actions/pr-script
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_commit: true
          commit_message: "auto run pre-commit"
          target: $${{ github.event.issue.html_url }}
