name: Sync
on:
  push:
    branches:
      - v1

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create a sync PR
        run: |
            git config --global github.user $GITHUB_ACTOR
            git config user.email $GITHUB_ACTOR@users.noreply.github.com
            git config user.name $GITHUB_ACTOR
            export AUTH_TOKEN=${{secrets.GITHUB_TOKEN}}
            sha=$(git rev-parse HEAD)
            bash ./etc/cherry-picker.sh $sha
