name: "Test"
on:
  workflow_dispatch:
  workflow_call:
jobs:
  prep_release:
    runs-on: ubuntu-latest
    outputs:
      job_id: ${{ steps.get-job-id.outputs.job_id }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -eux
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          git config user.email blink1073@users.noreply.github.com
          git config user.name "Test User"
          ip route get 8.8.8.8 | sed -n '/src/{s/.*src *\([^ ]*\).*/\1/p;q}'
          #git checkout -b test6
          #touch foo4.txt
          #git add .
          #git commit -a -m "test"
          #git push origin test6
          #gh pr create --fill
          #gh pr merge --squash https://github.com/blink1073/test-python-project/pull/38
          #git tag vtest3
          #git push origin --tags
      - name: Get Job ID from GH API
        id: get-job-id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
          echo "job_id=$job_id" >> $GITHUB_OUTPUT
          echo "hello there $job_id"
