name: "Push a commit"
on:
  workflow_dispatch:

jobs:
  push_commit:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4

      - run: |
          git checkout main
          echo "hello again!" > test.txt

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
