name: "Test"
on:
  workflow_dispatch:
jobs:
  prep_release:
    permissions: 
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - run: |
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          git config user.email blink1073@users.noreply.github.com
          git config user.name "Test User"
          git checkout -b test
          touch foo3.txt
          git add .
          git commit -a -m "test"
          git push origin test
          gh pr create --fill
          gh pr merge https://github.com/blink1073/test-python-project/pull/33
          git tag vtest2
          git push origin --tags
