name: "Test"
on:
  workflow_dispatch:
jobs:
  prep_release:
    permissions: 
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -eux
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          git config user.email blink1073@users.noreply.github.com
          git config user.name "Test User"
          ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'
          #git checkout -b test6
          #touch foo4.txt
          #git add .
          #git commit -a -m "test"
          #git push origin test6
          #gh pr create --fill
          #gh pr merge --squash https://github.com/blink1073/test-python-project/pull/38
          #git tag vtest3
          #git push origin --tags
