name: "Test"
on:
  workflow_dispatch:
jobs:
  prep_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - run: |
          touch foo.txt
          git config user.email blink1073@users.noreply.github.com
          git config user.name "Test User"
          git add foo.txt
          git commit -a -m "test add"
          git push origin main
