name: "Test"
on:
  workflow_dispatch:
jobs:
  prep_release:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - run: |
          git config user.email blink1073@users.noreply.github.com
          git config user.name "Test User"
          git tag vtest
          git push origin --tags
